'use strict';

var Component = {
    iHealthDeviceManagerModule: require('./module/iHealthDeviceManagerModule'),
    BP5Module: require('./module/BP5Module'),
    BP5SModule: require('./module/BP5SModule'),
    BP3LModule: require('./module/BP3LModule'),
    BP550BTModule: require('./module/BP550BTModule'),
    BP7Module: require('./module/BP7Module'),
    BP7SModule: require('./module/BP7SModule'),
    BPProfileModule: require('./module/BPProfileModule'),
    AM3SModule: require('./module/AM3SModule'),
    AM4Module: require('./module/AM4Module'),
    AMProfileModule: require('./module/AMProfileModule'),
    PO3Module: require('./module/PO3Module'),
    POProfileModule: require('./module/POProfileModule'),
    HS2Module: require('./module/HS2Module'),
    HS2SModule: require('./module/HS2SModule'),
    HS4SModule: require('./module/HS4SModule'),
    HSProfileModule: require('./module/HSProfileModule'),
    HS2SProfileModule: require('./module/HS2SProfileModule'),
    BG1Module: require('./module/BG1Module'),
    BG1ProfileModule: require('./module/BG1ProfileModule'),
    HS6Module: require('./module/HS6Module'),
    HS6ProfileModule: require('./module/HS6ProfileModule'),
    BG5Module:require('./module/BG5Module'),
    BG5SModule:require('./module/BG5SModule'),
    BG5SProfileModule:require('./module/BG5SProfileModule'),
    BGProfileModule:require('./module/BGProfileModule'),
    BTMModule:require('./module/BTMModule'),
    BTMProfileModule:require('./module/BTMProfileModule'),
    ECGModule:require('./module/ECGModule'),
    ECGUSBModule:require('./module/ECGUSBModule'),
    ECGProfileModule:require('./module/ECGProfileModule'),
    TS28BModule:require('./module/TS28BModule'),
    TS28BProfileModule:require('./module/TS28BProfileModule'),
    NT13BModule:require('./module/NT13BModule'),
    NT13BProfileModule:require('./module/NT13BProfileModule'),
    BG1SModule:require('./module/BG1SModule'),
    BG1SProfileModule:require('./module/BG1SProfileModule'),
    PO1Module:require('./module/PO1Module'),
    PO1ProfileModule:require('./module/PO1ProfileModule'),
    PT3SBTModule:require('./module/PT3SBTModule'),
    PT3SBTProfileModule:require('./module/PT3SBTProfileModule'),
}

module.exports = Component;
