'use strict';

var { NativeModules } = require('react-native');

var RCTModule = NativeModules.BG1SProfileModule

/**
 * @module BG1SProfileModule
 */
module.exports = {
  ACTION_GET_DEVICE_INFO: RCTModule.ACTION_GET_DEVICE_INFO,
  INFO_BATTERY_BG1S: RCTModule.INFO_BATTERY_BG1S,
  INFO_VERSION_CODE_BLOOD_BG1S: RCTModule.INFO_VERSION_CODE_BLOOD_BG1S,
  INFO_VERSION_CODE_CTL_BG1S: RCTModule.INFO_VERSION_CODE_CTL_BG1S,

  ACTION_STRIP_INSERTION_STATUS: RCTModule.ACTION_STRIP_INSERTION_STATUS,
  ACTION_GET_BLOOD: RCTModule.ACTION_GET_BLOOD,

  ACTION_SET_MEASURE_MODE: RCTModule.ACTION_SET_MEASURE_MODE,
  
  ACTION_MEASURE_RESULT: RCTModule.ACTION_SET_MEASURE_MODE,
  MEASURE_MODE: RCTModule.MEASURE_MODE,
  MEASURE_RESULT: RCTModule.MEASURE_RESULT,

  ACTION_ERROR_BG1S: RCTModule.ACTION_ERROR_BG1S,
  ERROR_NUM_BG1S: RCTModule.ERROR_NUM_BG1S,
  ERROR_DESCRIPTION_BG1S: RCTModule.ERROR_DESCRIPTION_BG1S,

  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES
}
