/**
 * Created by zhangxu on 16/11/16.
 */
'use strict';


var { NativeModules } = require('react-native');

var RCTModule = NativeModules.BPProfileModule

/**
 * @module BPProfileModule
 */
module.exports = {

    ACTION_ERROR_BP:RCTModule.ACTION_ERROR_BP,
    ERROR_NUM_BP:RCTModule.ERROR_NUM_BP,
    ERROR_DESCRIPTION_BP:RCTModule.ERROR_DESCRIPTION_BP,

    ACTION_BATTERY_BP:RCTModule.ACTION_BATTERY_BP,
    BATTERY_BP:RCTModule.BATTERY_BP,

    ACTION_ZOREING_BP:RCTModule.ACTION_ZOREING_BP,
    ACTION_ZOREOVER_BP:RCTModule.ACTION_ZOREOVER_BP,
    ACTION_ONLINE_PRESSURE_BP:RCTModule.ACTION_ONLINE_PRESSURE_BP,
    BLOOD_PRESSURE_BP:RCTModule.BLOOD_PRESSURE_BP,
    ACTION_ONLINE_PULSEWAVE_BP:RCTModule.ACTION_ONLINE_PULSEWAVE_BP,
    FLAG_HEARTBEAT_BP:RCTModule.FLAG_HEARTBEAT_BP,
    PULSEWAVE_BP:RCTModule.PULSEWAVE_BP,
    ACTION_ONLINE_RESULT_BP:RCTModule.ACTION_ONLINE_RESULT_BP,
    HIGH_BLOOD_PRESSURE_BP:RCTModule.HIGH_BLOOD_PRESSURE_BP,
    LOW_BLOOD_PRESSURE_BP:RCTModule.LOW_BLOOD_PRESSURE_BP,
    PULSE_BP:RCTModule.PULSE_BP,
    MEASUREMENT_AHR_BP:RCTModule.MEASUREMENT_AHR_BP,
    MEASUREMENT_HSD_BP:RCTModule.MEASUREMENT_HSD_BP,
    DATAID:RCTModule.DATAID,

    ACTION_HISTORICAL_NUM_BP:RCTModule.ACTION_HISTORICAL_NUM_BP,
    HISTORICAL_NUM_BP:RCTModule.HISTORICAL_NUM_BP,
    
    ACTION_HISTORICAL_DATA_BP:RCTModule.ACTION_HISTORICAL_DATA_BP,
    HISTORICAL_DATA_BP:RCTModule.HISTORICAL_DATA_BP,
    MEASUREMENT_DATE_BP:RCTModule.MEASUREMENT_DATE_BP,
    MEASUREMENT_STRAT_ANGLE_BP:RCTModule.MEASUREMENT_STRAT_ANGLE_BP,
    MEASUREMENT_ANGLE_CHANGE_BP:RCTModule.MEASUREMENT_ANGLE_CHANGE_BP,
    MEASUREMENT_HAND_BP:RCTModule.MEASUREMENT_HAND_BP,
    ACTION_HISTORICAL_OVER_BP:RCTModule.ACTION_HISTORICAL_OVER_BP,
    
    ACTION_FUNCTION_INFORMATION_BP:RCTModule.ACTION_FUNCTION_INFORMATION_BP,
    FUNCTION_IS_UPAIR_MEASURE:RCTModule.FUNCTION_IS_UPAIR_MEASURE,
    FUNCTION_IS_ARM_MEASURE:RCTModule.FUNCTION_IS_ARM_MEASURE,
    FUNCTION_HAVE_ANGLE_SENSOR:RCTModule.FUNCTION_HAVE_ANGLE_SENSOR,
    FUNCTION_HAVE_OFFLINE:RCTModule.FUNCTION_HAVE_OFFLINE,
    FUNCTION_HAVE_HSD:RCTModule.FUNCTION_HAVE_HSD,
    FUNCTION_HAVE_ANGLE_SETTING:RCTModule.FUNCTION_HAVE_ANGLE_SETTING,
    FUNCTION_IS_MULTI_UPLOAD:RCTModule.FUNCTION_IS_MULTI_UPLOAD,
    FUNCTION_HAVE_SELF_UPDATE:RCTModule.FUNCTION_HAVE_SELF_UPDATE,

    ACTION_SET_UNIT_SUCCESS_BP:RCTModule.ACTION_SET_UNIT_SUCCESS_BP,
    ACTION_SET_ANGLE_SUCCESS_BP:RCTModule.ACTION_SET_ANGLE_SUCCESS_BP,
    ACTION_ENABLE_OFFLINE_BP:RCTModule.ACTION_ENABLE_OFFLINE_BP,
    ACTION_DISENABLE_OFFLINE_BP:RCTModule.ACTION_DISENABLE_OFFLINE_BP,
    ACTION_IS_ENABLE_OFFLINE:RCTModule.ACTION_IS_ENABLE_OFFLINE,

    IS_ENABLE_OFFLINE:RCTModule.IS_ENABLE_OFFLINE,

    ACTION_INTERRUPTED_BP:RCTModule.ACTION_INTERRUPTED_BP,
    ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES
}
