/**
 * Created by lixuesong on 15/11/2016.
 */
'use strict';


var {NativeModules} = require('react-native');

var RCTModule = NativeModules.BTMProfileModule

/**
 * @module BTMProfileModule
 */
module.exports = {

  ACTION_BTM_BATTERY: RCTModule.ACTION_BTM_BATTERY,
  ACTION_BTM_MEMORY: RCTModule.ACTION_BTM_MEMORY,
  ACTION_BTM_MEASURE: RCTModule.ACTION_BTM_MEASURE,
  ACTION_BTM_CALLBACK: RCTModule.ACTION_BTM_CALLBACK,
  ACTION_ERROR_BTM: RCTModule.ACTION_ERROR_BTM,

  //Keys
  BTM_BATTERY: RCTModule.BTM_BATTERY,
  MEMORY_COUNT: RCTModule.MEMORY_COUNT,
  BTM_TEMPERATURE_ARRAY: RCTModule.BTM_TEMPERATURE_ARRAY,
  BTM_TEMPERATURE_TARGET: RCTModule.BTM_TEMPERATURE_TARGET,
  BTM_TEMPERATURE: RCTModule.BTM_TEMPERATURE,
  BTM_MEASURE_TIME: RCTModule.BTM_MEASURE_TIME,
  ERROR_NUM_BTM: RCTModule.ERROR_NUM_BTM,
  ERROR_DESCRIPTION_BTM: RCTModule.ERROR_DESCRIPTION_BTM,

  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES
}
