/**
 * Created by lixuesong on 15/11/2016.
 */
'use strict';


var {NativeModules} = require('react-native');

var RCTModule = NativeModules.HS6ProfileModule

/**
 * @module HS6ProfileModule
 */
module.exports = {

  ACTION_HS6_SETWIFI: RCTModule.ACTION_HS6_SETWIFI,
  ACTION_HS6_BIND: RCTModule.ACTION_HS6_BIND,
  ACTION_HS6_UNBIND: RCTModule.ACTION_HS6_UNBIND,
  ACTION_HS6_GET_TOKEN: RCTModule.ACTION_HS6_GET_TOKEN,
  ACTION_HS6_SET_UNIT: RCTModule.ACTION_HS6_SET_UNIT,

  ACTION_HS6_GET_CLOUDDATA:RCTModule.ACTION_HS6_GET_CLOUDDATA,
  HS6_CLOUDDATA:RCTModule.HS6_CLOUDDATA,

  ACTION_HS6_GET_CLOUDDATA_LASTTS:RCTModule.ACTION_HS6_GET_CLOUDDATA_LASTTS,
  HS6_CLOUDDATA_LASTTS:RCTModule.HS6_CLOUDDATA_LASTTS,

  ACTION_HS6_GET_CLOUDDATA_LEFTNUM:RCTModule.ACTION_HS6_GET_CLOUDDATA_LEFTNUM,
  HS6_CLOUDDATA_LEFTNUM:RCTModule.HS6_CLOUDDATA_LEFTNUM,

  ACTION_HS6_ERROR: RCTModule.ACTION_HS6_ERROR,
  ACTION_HS6_GET_DATA: RCTModule.ACTION_HS6_GET_DATA,

  //Keys
  SETWIFI_RESULT: RCTModule.SETWIFI_RESULT,
  HS6_BIND_EXTRA: RCTModule.HS6_BIND_EXTRA,
  BIND_HS6_RESULT: RCTModule.BIND_HS6_RESULT,
  HS6_MODEL: RCTModule.HS6_MODEL,
  HS6_POSITION: RCTModule.HS6_POSITION,
  HS6_SETTED_WIFI: RCTModule.HS6_SETTED_WIFI,
  HS6_UNBIND_RESULT: RCTModule.HS6_UNBIND_RESULT,
  GET_TOKEN_RESULT: RCTModule.GET_TOKEN_RESULT,
  SET_UNIT_RESULT: RCTModule.SET_UNIT_RESULT,
  HS6_ERROR: RCTModule.HS6_ERROR,

  DATA_RESULT: RCTModule.DATA_RESULT,
  DATA_DOWNLOAD_TS: RCTModule.DATA_DOWNLOAD_TS,

  DATA_LEFTNUMBER: RCTModule.DATA_LEFTNUMBER
}
