/**
 * Created by lixuesong on 15/11/2016.
 */
'use strict';


var {NativeModules} = require('react-native');

var RCTModule = NativeModules.HSProfileModule

/**
 * @module HSProfileModule
 */
module.exports = {

  ACTION_LIVEDATA_HS: RCTModule.ACTION_LIVEDATA_HS,
  ACTION_ONLINE_RESULT_HS: RCTModule.ACTION_ONLINE_RESULT_HS,
  ACTION_HISTORICAL_DATA_HS: RCTModule.ACTION_HISTORICAL_DATA_HS,
  ACTION_HISTORICAL_DATA_COMPLETE_HS: RCTModule.ACTION_HISTORICAL_DATA_COMPLETE_HS,
  ACTION_NO_HISTORICALDATA: RCTModule.ACTION_NO_HISTORICALDATA,
  ACTION_ERROR_HS: RCTModule.ACTION_ERROR_HS,

  //Keys
  LIVEDATA_HS: RCTModule.LIVEDATA_HS,
  DATAID: RCTModule.DATAID,
  WEIGHT_HS: RCTModule.WEIGHT_HS,
  FAT_HS: RCTModule.FAT_HS,
  WATER_HS: RCTModule.WATER_HS,
  MUSCLE_HS: RCTModule.MUSCLE_HS,
  SKELETON_HS: RCTModule.SKELETON_HS,
  FATELEVEL_HS: RCTModule.FATELEVEL_HS,
  DCI_HS: RCTModule.DCI_HS,
  HISTORDATA__HS: RCTModule.HISTORDATA__HS,
  MEASUREMENT_DATE_HS: RCTModule.MEASUREMENT_DATE_HS,

  ERROR_NUM_HS: RCTModule.ERROR_NUM_HS,
  ERROR_ID_ILLEGAL_ARGUMENT: RCTModule.ERROR_ID_ILLEGAL_ARGUMENT,
  ERROR_ID_WIFI_DISABLED: RCTModule.ERROR_ID_WIFI_DISABLED,
  ERROR_DESCRIPTION_HS: RCTModule.ERROR_DESCRIPTION_HS,

  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES
}
