'use strict';

var { NativeModules } = require('react-native');

var RCTModule = NativeModules.PT3SBTProfileModule

/**
 * @module PT3SBTProfileModule
 */
module.exports = {
  // actions
  ACTION_SET_TIME: RCTModule.ACTION_SET_TIME,
  ACTION_GET_BATTERY: RCTModule.ACTION_GET_BATTERY,
  ACTION_SET_UNIT: RCTModule.ACTION_SET_UNIT,
  ACTION_GET_UNIT: RCTModule.ACTION_GET_UNIT,
  ACTION_GET_HISTORY_COUNT: RCTModule.ACTION_GET_HISTORY_COUNT,
  ACTION_GET_HISTORY_DATA: RCTModule.ACTION_GET_HISTORY_DATA,
  ACTION_DELETE_HISTORY_DATA: RCTModule.ACTION_DELETE_HISTORY_DATA,
  ACTION_TEMPERATURE_MEASUREMENT: RCTModule.ACTION_TEMPERATURE_MEASUREMENT,
  ACTION_PUB_UNIT: RCTModule.ACTION_PUB_UNIT,
  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES,
  
  // keys
  STATUS: RCTModule.STATUS,
  BATTERY: RCTModule.BATTERY,
  UNIT: RCTModule.UNIT,
  TS: RCTModule.TS,
  COUNT: RCTModule.COUNT,
  TEMPERATURE: RCTModule.TEMPERATURE,
  HISTORY: RCTModule.HISTORY
}
