package com.ihealth.ihealthlibrary;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.module.annotations.ReactModule;
import com.ihealth.communication.control.AmProfile;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Nullable;

/**
 * Created by Jeepend on 15/11/2016.
 */
@ReactModule(name = "AMProfileModule")
public class AMProfileModule extends ReactContextBaseJavaModule {
    private static final String modelName = "AMProfileModule";
    private static final String TAG = "AMProfileModule";

    private static final String ACTION_ERROR_AM = "ACTION_ERROR_AM";
    private static final String ACTION_RESET_AM = "ACTION_RESET_AM";
    private static final String ACTION_USERID_AM = "ACTION_USERID_AM";
    private static final String ACTION_SET_USERID_SUCCESS_AM = "ACTION_SET_USERID_SUCCESS_AM";
    private static final String ACTION_SYNC_TIME_SUCCESS_AM = "ACTION_SYNC_TIME_SUCCESS_AM";
    private static final String ACTION_SET_USERINFO_SUCCESS_AM = "ACTION_SET_USERINFO_SUCCESS_AM";
    private static final String ACTION_GET_USERINFO_AM = "ACTION_GET_USERINFO_AM";
    private static final String ACTION_GET_ALARMNUM_AM = "ACTION_GET_ALARMNUM_AM";
    private static final String ACTION_GET_ALARMINFO_AM = "ACTION_GET_ALARMINFO_AM";
    private static final String ACTION_SET_ALARMINFO_SUCCESS_AM = "ACTION_SET_ALARMINFO_SUCCESS_AM";
    private static final String ACTION_DELETE_ALARM_SUCCESS_AM = "ACTION_DELETE_ALARM_SUCCESS_AM";
    private static final String ACTION_GET_ACTIVITY_REMIND_AM = "ACTION_GET_ACTIVITY_REMIND_AM";
    private static final String ACTION_SET_ACTIVITYREMIND_SUCCESS_AM = "ACTION_SET_ACTIVITYREMIND_SUCCESS_AM";
    private static final String ACTION_SYNC_ACTIVITY_DATA_AM = "ACTION_SYNC_ACTIVITY_DATA_AM";
    private static final String ACTION_SYNC_SLEEP_DATA_AM = "ACTION_SYNC_SLEEP_DATA_AM";
    private static final String ACTION_SYNC_STAGE_DATA_AM = "ACTION_SYNC_STAGE_DATA_AM";
    private static final String ACTION_QUERY_STATE_AM = "ACTION_QUERY_STATE_AM";
    private static final String ACTION_SYNC_REAL_DATA_AM = "ACTION_SYNC_REAL_DATA_AM";
    private static final String ACTION_SET_BMR_SUCCESS_AM = "ACTION_SET_BMR_SUCCESS_AM";
    private static final String ACTION_GET_SWIMINFO_AM = "ACTION_GET_SWIMINFO_AM";
    private static final String ACTION_SET_SWIMINFO_AM = "ACTION_SET_SWIMINFO_AM";
    private static final String ACTION_GET_RANDOM_AM = "ACTION_GET_RANDOM_AM";
    private static final String ACTION_SET_HOUR_MODE_SUCCESS_AM = "ACTION_SET_HOUR_MODE_SUCCESS_AM";
    private static final String ACTION_GET_HOUR_MODE_AM = "ACTION_GET_HOUR_MODE_AM";
    private static final String ACTION_SET_DEVICE_MODE_AM = "ACTION_SET_DEVICE_MODE_AM";
    private static final String ACTION_CLOUD_BINDING_AM_SUCCESS = "ACTION_CLOUD_BINDING_AM_SUCCESS";
    private static final String ACTION_CLOUD_BINDING_AM_FAIL = "ACTION_CLOUD_BINDING_AM_FAIL";
    private static final String ACTION_CLOUD_UNBINDING_AM_SUCCESS = "ACTION_CLOUD_UNBINDING_AM_SUCCESS";
    private static final String ACTION_CLOUD_UNBINDING_AM_FAIL = "ACTION_CLOUD_UNBINDING_AM_FAIL";
    private static final String ACTION_CLOUD_SEARCH_AM = "ACTION_CLOUD_SEARCH_AM";
    private static final String ACTION_CLOUD_SEARCH_FAIL_AM = "ACTION_CLOUD_SEARCH_FAIL_AM";
    private static final String ACTION_SET_PICTURE_SUCCESS_AM = "ACTION_SET_PICTURE_SUCCESS_AM";
    private static final String ACTION_GET_PICTURE_AM = "ACTION_GET_PICTURE_AM";

    private static final String ERROR_NUM_AM = "ERROR_NUM_AM";
    private static final String ERROR_ID_ILLEGAL_ARGUMENT = "ERROR_ID_ILLEGAL_ARGUMENT";
    private static final String ERROR_ID_VERSION_NOT_SUPPORT = "ERROR_ID_VERSION_NOT_SUPPORT";
    private static final String ERROR_DESCRIPTION_AM = "ERROR_DESCRIPTION_AM";
    private static final String RESET_AM = "RESET_AM";
    private static final String USERID_AM = "USERID_AM";
    private static final String GET_USER_AGE_AM = "GET_USER_AGE_AM";
    private static final String GET_USER_STEP_AM = "GET_USER_STEP_AM";
    private static final String GET_USER_HEIGHT_AM = "GET_USER_HEIGHT_AM";
    private static final String GET_USER_SEX_AM = "GET_USER_SEX_AM";
    private static final String GET_USER_WEIGHT_AM = "GET_USER_WEIGHT_AM";
    private static final String GET_USER_UNIT_AM = "GET_USER_UNIT_AM";
    private static final String GET_USER_TARGET1_AM = "GET_USER_TARGET1_AM";
    private static final String GET_USER_TARGET2_AM = "GET_USER_TARGET2_AM";
    private static final String GET_USER_TARGET3_AM = "GET_USER_TARGET3_AM";
    private static final String GET_USER_SWIMTARGET_AM = "GET_USER_SWIMTARGET_AM";
    private static final String GET_ALARMNUM_AM = "GET_ALARMNUM_AM";
    private static final String GET_ALARMNUM_ID_AM = "GET_ALARMNUM_ID_AM";
    private static final String GET_ALARM_CLOCK_DETAIL = "GET_ALARM_CLOCK_DETAIL";
    private static final String GET_ALARM_ID_AM = "GET_ALARM_ID_AM";
    private static final String GET_ALARM_TIME_AM = "GET_ALARM_TIME_AM";
    private static final String GET_ALARM_ISREPEAT_AM = "GET_ALARM_ISREPEAT_AM";
    private static final String GET_ALARM_WEEK_AM = "GET_ALARM_WEEK_AM";
    private static final String GET_ALARM_WEEK_SUNDAY_AM = "GET_ALARM_WEEK_SUNDAY_AM";
    private static final String GET_ALARM_WEEK_MONDAY_AM = "GET_ALARM_WEEK_MONDAY_AM";
    private static final String GET_ALARM_WEEK_TUESDAY_AM = "GET_ALARM_WEEK_TUESDAY_AM";
    private static final String GET_ALARM_WEEK_WEDNESDAY_AM = "GET_ALARM_WEEK_WEDNESDAY_AM";
    private static final String GET_ALARM_WEEK_THURSDAY_AM = "GET_ALARM_WEEK_THURSDAY_AM";
    private static final String GET_ALARM_WEEK_FRIDAY_AM = "GET_ALARM_WEEK_FRIDAY_AM";
    private static final String GET_ALARM_WEEK_SATURDAY_AM = "GET_ALARM_WEEK_SATURDAY_AM";
    private static final String GET_ALARM_ISON_AM = "GET_ALARM_ISON_AM";
    private static final String GET_ACTIVITY_REMIND_TIME_AM = "GET_ACTIVITY_REMIND_TIME_AM";
    private static final String GET_ACTIVITY_REMIND_ISON_AM = "GET_ACTIVITY_REMIND_ISON_AM";
    private static final String SYNC_ACTIVITY_DATA_AM = "SYNC_ACTIVITY_DATA_AM";
    private static final String SYNC_ACTIVITY_DATA_TIME_AM = "SYNC_ACTIVITY_DATA_TIME_AM";
    private static final String SYNC_ACTIVITY_DATA_STEP_AM = "SYNC_ACTIVITY_DATA_STEP_AM";
    private static final String SYNC_ACTIVITY_DATA_STEP_LENGTH_AM = "SYNC_ACTIVITY_DATA_STEP_LENGTH_AM";
    private static final String SYNC_ACTIVITY_DATA_CALORIE_AM = "SYNC_ACTIVITY_DATA_CALORIE_AM";
    private static final String SYNC_ACTIVITY_EACH_DATA_AM = "SYNC_ACTIVITY_EACH_DATA_AM";
    private static final String SYNC_SLEEP_DATA_AM = "SYNC_SLEEP_DATA_AM";
    private static final String SYNC_SLEEP_DATA_TIME_AM = "SYNC_SLEEP_DATA_TIME_AM";
    private static final String SYNC_SLEEP_DATA_LEVEL_AM = "SYNC_SLEEP_DATA_LEVEL_AM";
    private static final String SYNC_SLEEP_EACH_DATA_AM = "SYNC_SLEEP_EACH_DATA_AM";
    private static final String SYNC_STAGE_DATA_AM = "SYNC_STAGE_DATA_AM";
    private static final String SYNC_STAGE_DATA_TYPE_AM = "SYNC_STAGE_DATA_TYPE_AM";
    private static final String SYNC_STAGE_DATA_TYPE_WORKOUT_AM = "SYNC_STAGE_DATA_TYPE_WORKOUT_AM";
    private static final String SYNC_STAGE_DATA_TYPE_SLEEP_AM = "SYNC_STAGE_DATA_TYPE_SLEEP_AM";
    private static final String SYNC_STAGE_DATA_TYPE_SWIM_AM = "SYNC_STAGE_DATA_TYPE_SWIM_AM";
    private static final String SYNC_STAGE_DATA_TYPE_PAGE_VIEW_SUMMARY = "SYNC_STAGE_DATA_TYPE_PAGE_VIEW_SUMMARY";
    private static final String SYNC_STAGE_DATA_STOP_TIME_AM = "SYNC_STAGE_DATA_STOP_TIME_AM";
    private static final String SYNC_STAGE_DATA_USED_TIME_AM = "SYNC_STAGE_DATA_USED_TIME_AM";
    private static final String SYNC_STAGE_DATA_WORKOUT_STEP_AM = "SYNC_STAGE_DATA_WORKOUT_STEP_AM";
    private static final String SYNC_STAGE_DATA_DISTANCE_AM = "SYNC_STAGE_DATA_DISTANCE_AM";
    private static final String SYNC_STAGE_DATA_CALORIE_AM = "SYNC_STAGE_DATA_CALORIE_AM";
    private static final String SYNC_STAGE_DATA_SLEEP_EFFICIENCY_AM = "SYNC_STAGE_DATA_SLEEP_EFFICIENCY_AM";
    private static final String SYNC_STAGE_DATA_SLEEP_IS50MIN_AM = "SYNC_STAGE_DATA_SLEEP_IS50MIN_AM";
    private static final String SYNC_STAGE_DATA_SWIM_STROKE_AM = "SYNC_STAGE_DATA_SWIM_STROKE_AM";
    private static final String SYNC_STAGE_DATA_SWIM_PULL_TIMES_AM = "SYNC_STAGE_DATA_SWIM_PULL_TIMES_AM";
    private static final String SYNC_STAGE_DATA_SWIM_TURNS_AM = "SYNC_STAGE_DATA_SWIM_TURNS_AM";
    private static final String SYNC_STAGE_DATA_SWIMPOOL_LENGTH_AM = "SYNC_STAGE_DATA_SWIMPOOL_LENGTH_AM";
    private static final String SYNC_STAGE_DATA_SWIM_CUTINDIF_AM = "SYNC_STAGE_DATA_SWIM_CUTINDIF_AM";
    private static final String SYNC_STAGE_DATA_SWIM_CUTOUTDIF_AM = "SYNC_STAGE_DATA_SWIM_CUTOUTDIF_AM";
    private static final String SYNC_STAGE_DATA_SWIM_PROCESSFLAG_AM = "SYNC_STAGE_DATA_SWIM_PROCESSFLAG_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_DATE_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_DATE_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_STEP_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_STEP_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_DISTANCE_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_DISTANCE_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_CALORIE_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_CALORIE_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_TARGET_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_TARGET_AM";
    private static final String SYNC_STAGE_DATA_VIEW_SUMMARY_SWIM_AM = "SYNC_STAGE_DATA_VIEW_SUMMARY_SWIM_AM";
    private static final String QUERY_STATE_AM = "QUERY_STATE_AM";
    private static final String QUERY_BATTERY_AM = "QUERY_BATTERY_AM";
    private static final String SYNC_REAL_STEP_AM = "SYNC_REAL_STEP_AM";
    private static final String SYNC_REAL_CALORIE_AM = "SYNC_REAL_CALORIE_AM";
    private static final String SYNC_REAL_TOTALCALORIE_AM = "SYNC_REAL_TOTALCALORIE_AM";
    private static final String GET_SWIMLANE_LENGTH_AM = "GET_SWIMLANE_LENGTH_AM";
    private static final String GET_SWIM_SWITCH_AM = "GET_SWIM_SWITCH_AM";
    private static final String GET_SWIM_CUTOUT_HOUR_AM = "GET_SWIM_CUTOUT_HOUR_AM";
    private static final String GET_SWIM_CUTOUT_MINUTE_AM = "GET_SWIM_CUTOUT_MINUTE_AM";
    private static final String GET_SWIM_UNIT_AM = "GET_SWIM_UNIT_AM";
    private static final String GET_RANDOM_AM = "GET_RANDOM_AM";
    private static final String AM_SWITCH_OPEN = "AM_SWITCH_OPEN";
    private static final String AM_SWITCH_CLOSE = "AM_SWITCH_CLOSE";
    private static final String AM_SWITCH_REPEAT = "AM_SWITCH_REPEAT";
    private static final String AM_SEITCH_NOT_REPEAT = "AM_SEITCH_NOT_REPEAT";
    private static final String AM_SET_MALE = "AM_SET_MALE";
    private static final String AM_SET_FEMALE = "AM_SET_FEMALE";
    private static final String AM_SET_UNIT_METRIC = "AM_SET_UNIT_METRIC";
    private static final String AM_SET_UNIT_IMPERIAL_STANDARD = "AM_SET_UNIT_IMPERIAL_STANDARD";
    private static final String AM_SET_12_HOUR_MODE = "AM_SET_12_HOUR_MODE";
    private static final String AM_SET_24_HOUR_MODE = "AM_SET_24_HOUR_MODE";
    private static final String AM_SET_EUROPE_12_HOUR_MODE = "AM_SET_EUROPE_12_HOUR_MODE";
    private static final String AM_SET_EUROPE_24_HOUR_MODE = "AM_SET_EUROPE_24_HOUR_MODE";
    private static final String AM_SET_EXCEPT_EUROPE_12_HOUR_MODE = "AM_SET_EXCEPT_EUROPE_12_HOUR_MODE";
    private static final String AM_SET_EXCEPT_EUROPE_24_HOUR_MODE = "AM_SET_EXCEPT_EUROPE_24_HOUR_MODE";
    private static final String GET_HOUR_MODE_AM = "GET_HOUR_MODE_AM";
    private static final String AM_DEVICE_MODE_SLEEP = "AM_DEVICE_MODE_SLEEP";
    private static final String AM_DEVICE_MODE_ACTIVITY = "AM_DEVICE_MODE_ACTIVITY";
    private static final String AM_DEVICE_MODE_FLIGHT = "AM_DEVICE_MODE_FLIGHT";
    private static final String AM_DEVICE_MODE_DRIVING = "AM_DEVICE_MODE_DRIVING";
    private static final String CLOUD_SEARCH_AM = "CLOUD_SEARCH_AM";
    private static final String DATAID = "DATAID";
    private static final String GET_PICTURE_AM = "GET_PICTURE_AM";
    private static final String ACTION_GET_ALL_CONNECTED_DEVICES = "ACTION_GET_ALL_CONNECTED_DEVICES";


    public AMProfileModule(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public String getName() {
        return modelName;
    }

    @Nullable
    @Override
    public Map<String, Object> getConstants() {
        Map<String, Object> constants = new HashMap<>();
        constants.put(ACTION_ERROR_AM, AmProfile.ACTION_ERROR_AM);
        constants.put(ACTION_RESET_AM, AmProfile.ACTION_RESET_AM);
        constants.put(ACTION_USERID_AM, AmProfile.ACTION_USERID_AM);
        constants.put(ACTION_SET_USERID_SUCCESS_AM, AmProfile.ACTION_SET_USERID_SUCCESS_AM);
        constants.put(ACTION_SYNC_TIME_SUCCESS_AM, AmProfile.ACTION_SYNC_TIME_SUCCESS_AM);
        constants.put(ACTION_SET_USERINFO_SUCCESS_AM, AmProfile.ACTION_SET_USERINFO_SUCCESS_AM);
        constants.put(ACTION_GET_USERINFO_AM, AmProfile.ACTION_GET_USERINFO_AM);
        constants.put(ACTION_GET_ALARMNUM_AM, AmProfile.ACTION_GET_ALARMNUM_AM);
        constants.put(ACTION_GET_ALARMINFO_AM, AmProfile.ACTION_GET_ALARMINFO_AM);
        constants.put(ACTION_SET_ALARMINFO_SUCCESS_AM, AmProfile.ACTION_SET_ALARMINFO_SUCCESS_AM);
        constants.put(ACTION_DELETE_ALARM_SUCCESS_AM, AmProfile.ACTION_DELETE_ALARM_SUCCESS_AM);
        constants.put(ACTION_GET_ACTIVITY_REMIND_AM, AmProfile.ACTION_GET_ACTIVITY_REMIND_AM);
        constants.put(ACTION_SET_ACTIVITYREMIND_SUCCESS_AM, AmProfile.ACTION_SET_ACTIVITYREMIND_SUCCESS_AM);
        constants.put(ACTION_SYNC_ACTIVITY_DATA_AM, AmProfile.ACTION_SYNC_ACTIVITY_DATA_AM);
        constants.put(ACTION_SYNC_SLEEP_DATA_AM, AmProfile.ACTION_SYNC_SLEEP_DATA_AM);
        constants.put(ACTION_SYNC_STAGE_DATA_AM, AmProfile.ACTION_SYNC_STAGE_DATA_AM);
        constants.put(ACTION_QUERY_STATE_AM, AmProfile.ACTION_QUERY_STATE_AM);
        constants.put(ACTION_SYNC_REAL_DATA_AM, AmProfile.ACTION_SYNC_REAL_DATA_AM);
        constants.put(ACTION_SET_BMR_SUCCESS_AM, AmProfile.ACTION_SET_BMR_SUCCESS_AM);
        constants.put(ACTION_GET_SWIMINFO_AM, AmProfile.ACTION_GET_SWIMINFO_AM);
        constants.put(ACTION_SET_SWIMINFO_AM, AmProfile.ACTION_SET_SWIMINFO_AM);
        constants.put(ACTION_GET_RANDOM_AM, AmProfile.ACTION_GET_RANDOM_AM);
        constants.put(ACTION_SET_HOUR_MODE_SUCCESS_AM, AmProfile.ACTION_SET_HOUR_MODE_SUCCESS_AM);
        constants.put(ACTION_GET_HOUR_MODE_AM, AmProfile.ACTION_GET_HOUR_MODE_AM);
        constants.put(ACTION_SET_DEVICE_MODE_AM, AmProfile.ACTION_SET_DEVICE_MODE_AM);
        constants.put(ACTION_CLOUD_BINDING_AM_SUCCESS, AmProfile.ACTION_CLOUD_BINDING_AM_SUCCESS);
        constants.put(ACTION_CLOUD_BINDING_AM_FAIL, AmProfile.ACTION_CLOUD_BINDING_AM_FAIL);
        constants.put(ACTION_CLOUD_UNBINDING_AM_SUCCESS, AmProfile.ACTION_CLOUD_UNBINDING_AM_SUCCESS);
        constants.put(ACTION_CLOUD_UNBINDING_AM_FAIL, AmProfile.ACTION_CLOUD_UNBINDING_AM_FAIL);
        constants.put(ACTION_CLOUD_SEARCH_AM, AmProfile.ACTION_CLOUD_SEARCH_AM);
        constants.put(ACTION_CLOUD_SEARCH_FAIL_AM, AmProfile.ACTION_CLOUD_SEARCH_FAIL_AM);
        constants.put(ACTION_SET_PICTURE_SUCCESS_AM, AmProfile.ACTION_SET_PICTURE_SUCCESS_AM);
        constants.put(ACTION_GET_PICTURE_AM, AmProfile.ACTION_GET_PICTURE_AM);

        constants.put(ERROR_NUM_AM, AmProfile.ERROR_NUM_AM);
        constants.put(ERROR_ID_ILLEGAL_ARGUMENT, AmProfile.ERROR_ID_ILLEGAL_ARGUMENT);
        constants.put(ERROR_ID_VERSION_NOT_SUPPORT, AmProfile.ERROR_ID_VERSION_NOT_SUPPORT);
        constants.put(ERROR_DESCRIPTION_AM, AmProfile.ERROR_DESCRIPTION_AM);
        constants.put(RESET_AM, AmProfile.RESET_AM);
        constants.put(USERID_AM, AmProfile.USERID_AM);
        constants.put(GET_USER_AGE_AM, AmProfile.GET_USER_AGE_AM);
        constants.put(GET_USER_STEP_AM, AmProfile.GET_USER_STEP_AM);
        constants.put(GET_USER_HEIGHT_AM, AmProfile.GET_USER_HEIGHT_AM);
        constants.put(GET_USER_SEX_AM, AmProfile.GET_USER_SEX_AM);
        constants.put(GET_USER_WEIGHT_AM, AmProfile.GET_USER_WEIGHT_AM);
        constants.put(GET_USER_UNIT_AM, AmProfile.GET_USER_UNIT_AM);
        constants.put(GET_USER_TARGET1_AM, AmProfile.GET_USER_TARGET1_AM);
        constants.put(GET_USER_TARGET2_AM, AmProfile.GET_USER_TARGET2_AM);
        constants.put(GET_USER_TARGET3_AM, AmProfile.GET_USER_TARGET3_AM);
        constants.put(GET_USER_SWIMTARGET_AM, AmProfile.GET_USER_SWIMTARGET_AM);
        constants.put(GET_ALARMNUM_AM, AmProfile.GET_ALARMNUM_AM);
        constants.put(GET_ALARMNUM_ID_AM, AmProfile.GET_ALARMNUM_ID_AM);
        constants.put(GET_ALARM_CLOCK_DETAIL, AmProfile.GET_ALARM_CLOCK_DETAIL);
        constants.put(GET_ALARM_ID_AM, AmProfile.GET_ALARM_ID_AM);
        constants.put(GET_ALARM_TIME_AM, AmProfile.GET_ALARM_TIME_AM);
        constants.put(GET_ALARM_ISREPEAT_AM, AmProfile.GET_ALARM_ISREPEAT_AM);
        constants.put(GET_ALARM_WEEK_AM, AmProfile.GET_ALARM_WEEK_AM);
        constants.put(GET_ALARM_WEEK_SUNDAY_AM, AmProfile.GET_ALARM_WEEK_SUNDAY_AM);
        constants.put(GET_ALARM_WEEK_MONDAY_AM, AmProfile.GET_ALARM_WEEK_MONDAY_AM);
        constants.put(GET_ALARM_WEEK_TUESDAY_AM, AmProfile.GET_ALARM_WEEK_TUESDAY_AM);
        constants.put(GET_ALARM_WEEK_WEDNESDAY_AM, AmProfile.GET_ALARM_WEEK_WEDNESDAY_AM);
        constants.put(GET_ALARM_WEEK_THURSDAY_AM, AmProfile.GET_ALARM_WEEK_THURSDAY_AM);
        constants.put(GET_ALARM_WEEK_FRIDAY_AM, AmProfile.GET_ALARM_WEEK_FRIDAY_AM);
        constants.put(GET_ALARM_WEEK_SATURDAY_AM, AmProfile.GET_ALARM_WEEK_SATURDAY_AM);
        constants.put(GET_ALARM_ISON_AM, AmProfile.GET_ALARM_ISON_AM);
        constants.put(GET_ACTIVITY_REMIND_TIME_AM, AmProfile.GET_ACTIVITY_REMIND_TIME_AM);
        constants.put(GET_ACTIVITY_REMIND_ISON_AM, AmProfile.GET_ACTIVITY_REMIND_ISON_AM);
        constants.put(SYNC_ACTIVITY_DATA_AM, AmProfile.SYNC_ACTIVITY_DATA_AM);
        constants.put(SYNC_ACTIVITY_DATA_TIME_AM, AmProfile.SYNC_ACTIVITY_DATA_TIME_AM);
        constants.put(SYNC_ACTIVITY_DATA_STEP_AM, AmProfile.SYNC_ACTIVITY_DATA_STEP_AM);
        constants.put(SYNC_ACTIVITY_DATA_STEP_LENGTH_AM, AmProfile.SYNC_ACTIVITY_DATA_STEP_LENGTH_AM);
        constants.put(SYNC_ACTIVITY_DATA_CALORIE_AM, AmProfile.SYNC_ACTIVITY_DATA_CALORIE_AM);
        constants.put(SYNC_ACTIVITY_EACH_DATA_AM, AmProfile.SYNC_ACTIVITY_EACH_DATA_AM);
        constants.put(SYNC_SLEEP_DATA_AM, AmProfile.SYNC_SLEEP_DATA_AM);
        constants.put(SYNC_SLEEP_DATA_TIME_AM, AmProfile.SYNC_SLEEP_DATA_TIME_AM);
        constants.put(SYNC_SLEEP_DATA_LEVEL_AM, AmProfile.SYNC_SLEEP_DATA_LEVEL_AM);
        constants.put(SYNC_SLEEP_EACH_DATA_AM, AmProfile.SYNC_SLEEP_EACH_DATA_AM);
        constants.put(SYNC_STAGE_DATA_AM, AmProfile.SYNC_STAGE_DATA_AM);
        constants.put(SYNC_STAGE_DATA_TYPE_AM, AmProfile.SYNC_STAGE_DATA_TYPE_AM);
        constants.put(SYNC_STAGE_DATA_TYPE_WORKOUT_AM, AmProfile.SYNC_STAGE_DATA_TYPE_WORKOUT_AM);
        constants.put(SYNC_STAGE_DATA_TYPE_SLEEP_AM, AmProfile.SYNC_STAGE_DATA_TYPE_SLEEP_AM);
        constants.put(SYNC_STAGE_DATA_TYPE_SWIM_AM, AmProfile.SYNC_STAGE_DATA_TYPE_SWIM_AM);
        constants.put(SYNC_STAGE_DATA_TYPE_PAGE_VIEW_SUMMARY, AmProfile.SYNC_STAGE_DATA_TYPE_PAGE_VIEW_SUMMARY);
        constants.put(SYNC_STAGE_DATA_STOP_TIME_AM, AmProfile.SYNC_STAGE_DATA_STOP_TIME_AM);
        constants.put(SYNC_STAGE_DATA_USED_TIME_AM, AmProfile.SYNC_STAGE_DATA_USED_TIME_AM);
        constants.put(SYNC_STAGE_DATA_WORKOUT_STEP_AM, AmProfile.SYNC_STAGE_DATA_WORKOUT_STEP_AM);
        constants.put(SYNC_STAGE_DATA_DISTANCE_AM, AmProfile.SYNC_STAGE_DATA_DISTANCE_AM);
        constants.put(SYNC_STAGE_DATA_CALORIE_AM, AmProfile.SYNC_STAGE_DATA_CALORIE_AM);
        constants.put(SYNC_STAGE_DATA_SLEEP_EFFICIENCY_AM, AmProfile.SYNC_STAGE_DATA_SLEEP_EFFICIENCY_AM);
        constants.put(SYNC_STAGE_DATA_SLEEP_IS50MIN_AM, AmProfile.SYNC_STAGE_DATA_SLEEP_IS50MIN_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_STROKE_AM, AmProfile.SYNC_STAGE_DATA_SWIM_STROKE_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_PULL_TIMES_AM, AmProfile.SYNC_STAGE_DATA_SWIM_PULL_TIMES_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_TURNS_AM, AmProfile.SYNC_STAGE_DATA_SWIM_TURNS_AM);
        constants.put(SYNC_STAGE_DATA_SWIMPOOL_LENGTH_AM, AmProfile.SYNC_STAGE_DATA_SWIMPOOL_LENGTH_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_CUTINDIF_AM, AmProfile.SYNC_STAGE_DATA_SWIM_CUTINDIF_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_CUTOUTDIF_AM, AmProfile.SYNC_STAGE_DATA_SWIM_CUTOUTDIF_AM);
        constants.put(SYNC_STAGE_DATA_SWIM_PROCESSFLAG_AM, AmProfile.SYNC_STAGE_DATA_SWIM_PROCESSFLAG_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_DATE_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_DATE_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_STEP_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_STEP_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_DISTANCE_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_DISTANCE_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_CALORIE_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_CALORIE_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_TARGET_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_TARGET_AM);
        constants.put(SYNC_STAGE_DATA_VIEW_SUMMARY_SWIM_AM, AmProfile.SYNC_STAGE_DATA_VIEW_SUMMARY_SWIM_AM);
        constants.put(QUERY_STATE_AM, AmProfile.QUERY_STATE_AM);
        constants.put(QUERY_BATTERY_AM, AmProfile.QUERY_BATTERY_AM);
        constants.put(SYNC_REAL_STEP_AM, AmProfile.SYNC_REAL_STEP_AM);
        constants.put(SYNC_REAL_CALORIE_AM, AmProfile.SYNC_REAL_CALORIE_AM);
        constants.put(SYNC_REAL_TOTALCALORIE_AM, AmProfile.SYNC_REAL_TOTALCALORIE_AM);
        constants.put(GET_SWIMLANE_LENGTH_AM, AmProfile.GET_SWIMLANE_LENGTH_AM);
        constants.put(GET_SWIM_SWITCH_AM, AmProfile.GET_SWIM_SWITCH_AM);
        constants.put(GET_SWIM_CUTOUT_HOUR_AM, AmProfile.GET_SWIM_CUTOUT_HOUR_AM);
        constants.put(GET_SWIM_CUTOUT_MINUTE_AM, AmProfile.GET_SWIM_CUTOUT_MINUTE_AM);
        constants.put(GET_SWIM_UNIT_AM, AmProfile.GET_SWIM_UNIT_AM);
        constants.put(GET_RANDOM_AM, AmProfile.GET_RANDOM_AM);
        constants.put(AM_SWITCH_OPEN, AmProfile.AM_SWITCH_OPEN);
        constants.put(AM_SWITCH_CLOSE, AmProfile.AM_SWITCH_CLOSE);
        constants.put(AM_SWITCH_REPEAT, AmProfile.AM_SWITCH_REPEAT);
        constants.put(AM_SEITCH_NOT_REPEAT, AmProfile.AM_SEITCH_NOT_REPEAT);
        constants.put(AM_SET_MALE, AmProfile.AM_SET_MALE);
        constants.put(AM_SET_FEMALE, AmProfile.AM_SET_FEMALE);
        constants.put(AM_SET_UNIT_METRIC, AmProfile.AM_SET_UNIT_METRIC);
        constants.put(AM_SET_UNIT_IMPERIAL_STANDARD, AmProfile.AM_SET_UNIT_IMPERIAL_STANDARD);
        constants.put(AM_SET_12_HOUR_MODE, AmProfile.AM_SET_12_HOUR_MODE);
        constants.put(AM_SET_24_HOUR_MODE, AmProfile.AM_SET_24_HOUR_MODE);
        constants.put(AM_SET_EUROPE_12_HOUR_MODE, AmProfile.AM_SET_EUROPE_12_HOUR_MODE);
        constants.put(AM_SET_EUROPE_24_HOUR_MODE, AmProfile.AM_SET_EUROPE_24_HOUR_MODE);
        constants.put(AM_SET_EXCEPT_EUROPE_12_HOUR_MODE, AmProfile.AM_SET_EXCEPT_EUROPE_12_HOUR_MODE);
        constants.put(AM_SET_EXCEPT_EUROPE_24_HOUR_MODE, AmProfile.AM_SET_EXCEPT_EUROPE_24_HOUR_MODE);
        constants.put(GET_HOUR_MODE_AM, AmProfile.GET_HOUR_MODE_AM);
        constants.put(AM_DEVICE_MODE_SLEEP, AmProfile.AM_DEVICE_MODE_SLEEP);
        constants.put(AM_DEVICE_MODE_ACTIVITY, AmProfile.AM_DEVICE_MODE_ACTIVITY);
        constants.put(AM_DEVICE_MODE_FLIGHT, AmProfile.AM_DEVICE_MODE_FLIGHT);
        constants.put(AM_DEVICE_MODE_DRIVING, AmProfile.AM_DEVICE_MODE_DRIVING);
        constants.put(CLOUD_SEARCH_AM, AmProfile.CLOUD_SEARCH_AM);
        constants.put(DATAID, AmProfile.DATAID);
        constants.put(GET_PICTURE_AM, AmProfile.GET_PICTURE_AM);
        constants.put(ACTION_GET_ALL_CONNECTED_DEVICES, iHealthBaseModule.ACTION_GET_ALL_CONNECTED_DEVICES);
        return constants;
    }
}
